<?php

return [
    'brand' => [
        'name' => 'BusinessOS',
        'tagline' => 'Modern software. Serious engineering. Fast everywhere.',
        'description' => 'BusinessOS builds business software and custom digital solutions including websites, ERP, MIS, web applications, data migration, modernization, integrations, automation, analytics and industry-specific systems.',
    ],

    'apps' => [
        'fieldpulse' => [
            'name' => 'FieldPulse',
            'slug' => 'fieldpulse',
            'icon_letter' => 'F',
            'eyebrow' => 'Field Sales & Operations',
            'headline' => 'Field sales tracking built for teams that work outside the office.',
            'short_description' => 'Give managers a clear view of attendance, client visits, routes, location history, and field performance without forcing field teams into a desktop-first workflow.',
            'description' => 'FieldPulse is a field sales and field force management platform for organizations that need to coordinate mobile sales teams, verify field activity, understand client visits, and keep operating when connectivity is unreliable.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web, Android, iOS',
            'platforms' => ['Web', 'Android', 'iOS'],
            'status' => 'Active development',
            'featured' => true,
            'accent' => 'blue',
            'web_url' => 'https://fieldpulse.businessos.af',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'FieldPulse — Field Sales Tracking & Field Force Management Software',
                'description' => 'Track field sales attendance, client visits, GPS activity, routes and team performance with FieldPulse, built for mobile teams and unreliable connectivity.',
            ],
            'translations' => [
                'fa' => [
                    'name' => 'FieldPulse',
                    'eyebrow' => 'فروش ساحوی و عملیات',
                    'headline' => 'ردیابی فروش ساحوی برای تیم‌هایی که بیرون از دفتر کار می‌کنند.',
                    'short_description' => 'حاضری، بازدید مشتریان، مسیرها و فعالیت ساحوی را در یک جریان کاری موبایل‌محور مدیریت کنید.',
                    'description' => 'FieldPulse پلتفرم مدیریت فروش و نیروی ساحوی برای هماهنگی تیم‌های موبایل، بازدید مشتریان و دید مدیریتی است.',
                    'seo_title' => 'FieldPulse — نرم‌افزار ردیابی فروش ساحوی',
                    'seo_description' => 'حاضری، بازدید مشتریان، موقعیت و عملکرد تیم ساحوی را با FieldPulse مدیریت کنید.',
                ],
                'ps' => [
                    'name' => 'FieldPulse',
                    'eyebrow' => 'ساحوي پلور او عملیات',
                    'headline' => 'د هغو ټیمونو لپاره د ساحوي پلور تعقیب چې له دفتره بهر کار کوي.',
                    'short_description' => 'حاضري، د پیرودونکو لیدنې، لارې او ساحوي فعالیت په موبایل-محور کاري بهیر کې اداره کړئ.',
                    'description' => 'FieldPulse د ساحوي پلور او ګرځنده ټیمونو د مدیریت لپاره یو پلاتفورم دی.',
                    'seo_title' => 'FieldPulse — د ساحوي پلور تعقیب سافټویر',
                    'seo_description' => 'د FieldPulse له لارې د ساحوي ټیم حاضري، پیرودونکي، موقعیت او فعالیت اداره کړئ.',
                ],
            ],
            'preview' => [
                'section' => 'Field operations',
                'title' => 'Team activity',
                'status' => 'Live',
                'metrics' => [
                    ['label' => 'Attendance', 'value' => 'Visible', 'detail' => 'work sessions'],
                    ['label' => 'Client visits', 'value' => 'Tracked', 'detail' => 'field execution'],
                    ['label' => 'Sync', 'value' => 'Ready', 'detail' => 'offline-aware'],
                ],
                'rows' => ['Attendance & shifts', 'Client visit history', 'Routes & live map'],
            ],
            'highlights' => [
                'Offline-first field workflows',
                'Attendance and work sessions',
                'GPS and client-visit history',
                'Live manager visibility',
            ],
            'problem' => [
                'title' => 'Field work becomes difficult to manage when activity is scattered across calls, chats and manual reports.',
                'body' => [
                    'Managers need reliable visibility into attendance, customer visits and territory activity without adding unnecessary friction for field staff.',
                    'FieldPulse connects those signals in one operational workflow while keeping mobile execution practical for teams working away from the office.',
                ],
            ],
            'features_intro' => [
                'title' => 'Built around the field day, not the office desk.',
                'description' => 'Each capability answers a real operational question without burying teams in unnecessary complexity.',
            ],
            'features' => [
                [
                    'title' => 'Field activity visibility',
                    'description' => 'See where field activity is happening, review location history, and understand how the team is covering customers and territories.',
                ],
                [
                    'title' => 'Attendance & work sessions',
                    'description' => 'Record the start and end of field work with operational context designed for teams that spend their day away from a central office.',
                ],
                [
                    'title' => 'Client visit tracking',
                    'description' => 'Connect visits to customers and locations so managers can review actual field execution instead of relying on fragmented manual reports.',
                ],
                [
                    'title' => 'Offline-first mobile operation',
                    'description' => 'Keep essential workflows usable when mobile internet is slow or temporarily unavailable, then synchronize safely when connectivity returns.',
                ],
                [
                    'title' => 'Admin dashboard & live map',
                    'description' => 'Give operations and sales managers one place to review field coverage, people, customers and activity signals.',
                ],
                [
                    'title' => 'AI-assisted insights',
                    'description' => 'Ask operational questions in natural language and use AI-assisted analysis as an additional layer on top of structured sales and field data.',
                ],
            ],
            'use_cases_intro' => [
                'title' => 'One field platform, several daily questions answered.',
                'description' => 'Use FieldPulse where visibility, accountability and mobile execution need to stay connected.',
            ],
            'use_cases' => [
                'Sales representative tracking',
                'Client visit verification',
                'Field attendance',
                'Territory coverage',
                'Sales route visibility',
                'Field-team performance review',
            ],
            'spotlight' => [
                'kicker' => 'Designed for imperfect connectivity',
                'title' => 'Work should not stop when the signal does.',
                'description' => 'FieldPulse is being built around offline-first mobile foundations so essential workflows can continue through unreliable connections and synchronize when the network is available again.',
                'items' => ['Offline-aware', 'Mobile-first', 'Safe synchronization'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing in preparation',
                'pricing_note' => 'FieldPulse pricing will be published when the commercial package is finalized. Team size, rollout requirements and deployment context can be discussed now without inventing a public list price.',
                'pricing_model' => 'Per field user + annual platform',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Customer domain/subdomain connection', 'Guided team onboarding'],
            ],
            'final' => [
                'title' => 'Make field activity easier to see, understand and manage.',
                'description' => 'Tell us about your field team and the workflow you want to improve. We will keep the conversation aligned with the current FieldPulse release state.',
            ],
            'faq' => [
                [
                    'question' => 'Is FieldPulse available as a finished public product?',
                    'answer' => 'FieldPulse is currently in active development. Demo and deployment discussions should reflect the current release state rather than presenting the product as generally available before it is ready.',
                ],
                [
                    'question' => 'Can FieldPulse work with unreliable mobile internet?',
                    'answer' => 'FieldPulse is being built on an offline-first mobile foundation so essential field workflows can continue during connectivity gaps and synchronize when a connection returns.',
                ],
                [
                    'question' => 'What kinds of teams is FieldPulse designed for?',
                    'answer' => 'FieldPulse is designed for organizations managing field sales or field operations where attendance, client visits, routes, location history and manager visibility need to stay connected.',
                ],
                [
                    'question' => 'How will FieldPulse pricing work?',
                    'answer' => 'The final commercial package has not been published yet. Pricing is intended to reflect the product, team size and deployment requirements rather than using placeholder prices that have not been approved.',
                ],
            ],
        ],

        'erp' => [
            'name' => 'BusinessOS ERP',
            'slug' => 'erp',
            'icon_letter' => 'E',
            'eyebrow' => 'ERP & Business Management',
            'headline' => 'Keep customers, sales, payments and business records connected.',
            'short_description' => 'Manage customers, products, quotations, invoices, payments and expenses from one web-based business system with customer ledgers and multi-business switching.',
            'description' => 'BusinessOS ERP is a web-based business management application for day-to-day commercial operations. The current live system includes customers and statements, products, quotations, invoicing, payments and reversals, expenses and reporting, currencies, exchange rates, and business switching.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Live',
            'featured' => false,
            'accent' => 'blue',
            'web_url' => 'https://erp.businessos.af',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'BusinessOS ERP — Customers, Quotations, Invoices, Payments & Expenses',
                'description' => 'Run customers, products, quotations, invoices, payments, expenses and business records in the BusinessOS ERP web application.',
            ],
            'translations' => [
                'fa' => [
                    'name' => 'BusinessOS ERP',
                    'eyebrow' => 'ERP و مدیریت تجارت',
                    'headline' => 'مشتریان، فروش، پرداخت‌ها و سوابق تجارت را متصل نگه دارید.',
                    'short_description' => 'مشتریان، محصولات، قیمت‌نامه‌ها، فاکتورها، پرداخت‌ها و مصارف را در یک سیستم تحت وب مدیریت کنید.',
                    'description' => 'BusinessOS ERP برنامه مدیریت تجارت برای مشتریان، محصولات، قیمت‌نامه‌ها، فاکتورها، پرداخت‌ها، مصارف و سوابق مالی است.',
                    'seo_title' => 'BusinessOS ERP — مدیریت مشتریان، فروش و پرداخت‌ها',
                    'seo_description' => 'عملیات تجارتی را با ERP برای مشتریان، قیمت‌نامه‌ها، فاکتورها، پرداخت‌ها و مصارف مدیریت کنید.',
                ],
                'ps' => [
                    'name' => 'BusinessOS ERP',
                    'eyebrow' => 'ERP او د سوداګرۍ مدیریت',
                    'headline' => 'پیرودونکي، پلور، تادیات او سوداګریز ریکارډونه سره ونښلوئ.',
                    'short_description' => 'پیرودونکي، محصولات، نرخونه، انوایسونه، تادیات او لګښتونه په یوه ویب سیسټم کې اداره کړئ.',
                    'description' => 'BusinessOS ERP د ورځنیو سوداګریزو عملیاتو لپاره د مدیریت ویب اپ دی.',
                    'seo_title' => 'BusinessOS ERP — د پیرودونکو، پلور او تادیاتو مدیریت',
                    'seo_description' => 'پیرودونکي، نرخونه، انوایسونه، تادیات او لګښتونه په BusinessOS ERP کې اداره کړئ.',
                ],
            ],
            'preview' => [
                'section' => 'Business management',
                'title' => 'Commercial overview',
                'status' => 'Live',
                'metrics' => [
                    ['label' => 'Customers', 'value' => 'Managed', 'detail' => 'ledger & statements'],
                    ['label' => 'Sales', 'value' => 'Connected', 'detail' => 'quotes & invoices'],
                    ['label' => 'Cash flow', 'value' => 'Tracked', 'detail' => 'payments & expenses'],
                ],
                'rows' => ['Customer ledgers', 'Quotation to invoice', 'Business switching'],
            ],
            'highlights' => [
                'Customer ledgers & statements',
                'Quotations and invoicing',
                'Payments, reversals & expenses',
                'Multi-business switching',
            ],
            'problem' => [
                'title' => 'Business records become unreliable when customers, sales and cash movements live in separate places.',
                'body' => [
                    'Teams lose time reconciling quotations, invoices, payments, customer balances and expenses when each workflow is maintained independently.',
                    'BusinessOS ERP keeps core commercial records connected so the business can move from customer activity to quotation, invoice, payment and reporting with a clearer audit trail.',
                ],
            ],
            'features_intro' => [
                'title' => 'Core business workflows in one connected system.',
                'description' => 'The live ERP focuses on practical commercial operations that businesses use every day.',
            ],
            'features' => [
                [
                    'title' => 'Customers, ledgers & statements',
                    'description' => 'Maintain customer records, review ledgers and generate statements so balances and commercial history stay connected.',
                ],
                [
                    'title' => 'Products & structured imports',
                    'description' => 'Maintain product records and use import workflows for faster setup and ongoing data management.',
                ],
                [
                    'title' => 'Quotations to invoices',
                    'description' => 'Create quotations, manage revisions and convert approved commercial work into invoices without re-entering the same information.',
                ],
                [
                    'title' => 'Payments & reversals',
                    'description' => 'Record payments against business activity and reverse transactions when corrections are required.',
                ],
                [
                    'title' => 'Expenses & reports',
                    'description' => 'Capture business expenses, review individual records and use expense reporting to understand operational outflow.',
                ],
                [
                    'title' => 'Business and currency settings',
                    'description' => 'Switch between configured businesses and maintain operational settings including currencies and exchange rates.',
                ],
            ],
            'use_cases_intro' => [
                'title' => 'A practical operating system for everyday business administration.',
                'description' => 'Use BusinessOS ERP when customer, sales and cash records need to stay connected across the daily commercial workflow.',
            ],
            'use_cases' => [
                'Customer account management',
                'Quotation and invoice workflows',
                'Receivable and payment tracking',
                'Expense recording and reporting',
                'Product master data',
                'Multiple business operations',
            ],
            'spotlight' => [
                'kicker' => 'Connected commercial flow',
                'title' => 'Move from customer to payment without rebuilding the record at every step.',
                'description' => 'The ERP links the common commercial sequence—customer, quotation, invoice, payment and ledger—while keeping expenses and reporting close to the same operational context.',
                'items' => ['Customer → quotation', 'Invoice → payment', 'Ledger → statement'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing in preparation',
                'pricing_note' => 'BusinessOS ERP pricing is not yet published publicly. Deployment scope, business structure and operational requirements can be discussed directly.',
                'pricing_model' => 'Deployment and module scope',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Dedicated customer subdomain', 'Data import and onboarding'],
            ],
            'final' => [
                'title' => 'Bring the daily business record into one connected workflow.',
                'description' => 'Open the live ERP or request a product discussion around the customer, sales and accounting workflows your business needs.',
            ],
            'faq' => [
                [
                    'question' => 'Is BusinessOS ERP live?',
                    'answer' => 'Yes. The ERP web application is live at erp.businessos.af and currently exposes customer, product, quotation, invoice, payment, expense and settings workflows.',
                ],
                [
                    'question' => 'Can the ERP handle more than one business?',
                    'answer' => 'The current live application includes business switching so configured businesses can be selected from the same application environment.',
                ],
                [
                    'question' => 'Does the ERP include customer ledgers and statements?',
                    'answer' => 'Yes. The deployed application includes customer ledger and customer statement routes in addition to customer management.',
                ],
                [
                    'question' => 'How is ERP pricing handled?',
                    'answer' => 'Public pricing has not been finalized. Pricing discussions should reflect deployment scope, business requirements and the modules being used.',
                ],
            ],
        ],

        'pos' => [
            'name' => 'BusinessOS POS',
            'slug' => 'pos',
            'icon_letter' => 'P',
            'eyebrow' => 'Retail POS & Inventory',
            'headline' => 'Retail checkout and stock management designed for Afghanistan.',
            'short_description' => 'A supermarket and retail POS direction built around AFN, English/Dari/Pashto, inventory, purchasing, cash management and reliable daily closing.',
            'description' => 'BusinessOS POS is the Laravel retail point-of-sale product for supermarkets and shops in Afghanistan. The live pilot is built around AFN-only operation, English/Dari/Pashto interfaces, inventory and purchasing, cash management, daily closing and checkout reliability.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Pilot ready',
            'featured' => false,
            'accent' => 'blue',
            'web_url' => 'https://dukan.businessos.af',
            'live_note' => 'The live BusinessOS POS pilot is available at dukan.businessos.af. The legacy pos.businessos.af installation is retained separately for compatibility and rollback.',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'BusinessOS POS — Supermarket POS & Inventory for Afghanistan',
                'description' => 'BusinessOS POS is a retail checkout, inventory, purchasing, cash-management and daily-closing product designed for shops and supermarkets in Afghanistan.',
            ],
            'translations' => [
                'fa' => [
                    'name' => 'BusinessOS POS',
                    'eyebrow' => 'فروشگاه، POS و موجودی',
                    'headline' => 'فروش و مدیریت موجودی برای دکان‌ها و سوپرمارکیت‌های افغانستان.',
                    'short_description' => 'فروش، موجودی، خرید، مدیریت نقدی و بسته‌شدن روزانه را با AFN و رابط‌های محلی مدیریت کنید.',
                    'description' => 'BusinessOS POS محصول فروشگاهی برای دکان‌ها و سوپرمارکیت‌ها با تمرکز بر AFN، موجودی، خرید، صندوق و گزارش روزانه است.',
                    'seo_title' => 'BusinessOS POS — سیستم فروش و موجودی برای افغانستان',
                    'seo_description' => 'فروش، موجودی، خرید و صندوق را با BusinessOS POS مدیریت کنید.',
                ],
                'ps' => [
                    'name' => 'BusinessOS POS',
                    'eyebrow' => 'پرچون، POS او ذخیره',
                    'headline' => 'د افغانستان د دوکانونو او سوپرمارکېټونو لپاره پلور او ذخیره.',
                    'short_description' => 'پلور، ذخیره، پېرود، نغدي مدیریت او ورځنی بندښت د AFN او محلي ژبو له لارې اداره کړئ.',
                    'description' => 'BusinessOS POS د دوکانونو او سوپرمارکېټونو لپاره د پلور، ذخیرې، پېرود او نغدو مدیریت محصول دی.',
                    'seo_title' => 'BusinessOS POS — د افغانستان لپاره د پلور او ذخیرې سیستم',
                    'seo_description' => 'پلور، ذخیره، پېرود او نغدي مدیریت د BusinessOS POS له لارې اداره کړئ.',
                ],
            ],
            'preview' => [
                'section' => 'Retail operations',
                'title' => 'Point of sale',
                'status' => 'Pilot',
                'metrics' => [
                    ['label' => 'Checkout', 'value' => 'Focused', 'detail' => 'reliable sales flow'],
                    ['label' => 'Inventory', 'value' => 'Connected', 'detail' => 'stock & purchasing'],
                    ['label' => 'Closing', 'value' => 'Daily', 'detail' => 'cash control'],
                ],
                'rows' => ['Fast checkout', 'Inventory & purchasing', 'Daily cash closing'],
            ],
            'highlights' => [
                'AFN-only retail operation',
                'Inventory and purchasing',
                'Cash management & daily closing',
                'English, Dari & Pashto',
            ],
            'problem' => [
                'title' => 'Retail software should match the way local shops actually sell, stock and close the day.',
                'body' => [
                    'Generic POS products often bring unnecessary tax assumptions, currency complexity or workflows that do not match supermarket operations in Afghanistan.',
                    'BusinessOS POS is built around local retail requirements: AFN, multilingual interfaces, dependable checkout, inventory control, purchasing and disciplined daily closing.',
                ],
            ],
            'features_intro' => [
                'title' => 'Built around checkout accuracy and stock correctness.',
                'description' => 'The modern Laravel POS prioritizes financial correctness, inventory correctness, auditability and checkout reliability before visual extras.',
            ],
            'features' => [
                [
                    'title' => 'Retail checkout',
                    'description' => 'A focused point-of-sale workflow designed to keep sales entry fast and reliable at the counter.',
                ],
                [
                    'title' => 'Inventory management',
                    'description' => 'Keep product stock connected to sales activity so retail teams can understand what is available and what has moved.',
                ],
                [
                    'title' => 'Purchasing',
                    'description' => 'Support stock replenishment through purchasing workflows that connect procurement with retail inventory.',
                ],
                [
                    'title' => 'Cash management & closing',
                    'description' => 'Support controlled cash handling and daily closing so each retail day can be reconciled consistently.',
                ],
                [
                    'title' => 'Afghanistan-localized operation',
                    'description' => 'Use AFN as the operating currency with no sales-tax workflow and interfaces planned for English, Dari and Pashto.',
                ],
                [
                    'title' => 'Responsive custom interface',
                    'description' => 'The Laravel application uses a custom Blade, Tailwind and Alpine interface designed for a modern browser-based retail experience.',
                ],
            ],
            'use_cases_intro' => [
                'title' => 'A focused operating system for supermarkets and retail shops.',
                'description' => 'Use BusinessOS POS where checkout, stock, purchasing and end-of-day cash control need to stay connected.',
            ],
            'use_cases' => [
                'Supermarket checkout',
                'Retail product sales',
                'Inventory control',
                'Purchasing and replenishment',
                'Cash management',
                'Daily closing',
            ],
            'spotlight' => [
                'kicker' => 'Designed for Afghanistan',
                'title' => 'Local rules should be product defaults, not workarounds.',
                'description' => 'The modern POS is designed around AFN-only operation, no sales-tax workflow, Asia/Kabul business time and English/Dari/Pashto interfaces.',
                'items' => ['AFN only', 'No sales-tax workflow', 'EN · Dari · Pashto'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing in preparation',
                'pricing_note' => 'The BusinessOS POS commercial package has not been published yet. Pricing will be aligned with the live Laravel release and deployment requirements.',
                'pricing_model' => 'Shop license + deployment',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Dukan subdomain access', 'Catalog import and first-shop onboarding'],
            ],
            'final' => [
                'title' => 'Give retail teams a faster path from checkout to daily closing.',
                'description' => 'Open the live Dukan pilot or request a discussion about rolling out BusinessOS POS for your supermarket or retail operation.',
            ],
            'faq' => [
                [
                    'question' => 'Is BusinessOS POS already live?',
                    'answer' => 'Yes. The Laravel BusinessOS POS pilot is live at dukan.businessos.af. The legacy pos.businessos.af installation is retained separately while the new release completes checkout UAT.',
                ],
                [
                    'question' => 'Which currency is the modern POS designed for?',
                    'answer' => 'The Laravel POS is designed for AFN-only operation.',
                ],
                [
                    'question' => 'Which languages are planned for BusinessOS POS?',
                    'answer' => 'The product is designed for English, Dari and Pashto, with right-to-left presentation for Dari and Pashto.',
                ],
                [
                    'question' => 'Does the modern POS include sales tax?',
                    'answer' => 'No. The product rules intentionally do not implement a sales-tax, VAT or GST workflow.',
                ],
            ],
        ],
        'pharmacy-management' => [
            'name' => 'Pharmacy Management System',
            'slug' => 'pharmacy-management',
            'icon_letter' => 'P',
            'eyebrow' => 'Pharmacy Operations',
            'headline' => 'Manage pharmacy inventory, purchasing, sales and financial visibility in one system.',
            'short_description' => 'A customizable pharmacy management platform for medicine inventory, batch and expiry tracking, suppliers, purchasing, sales, receivables and operational reporting.',
            'description' => 'BusinessOS Pharmacy Management System is designed for pharmacies and medicine businesses that need clearer control over stock, expiry dates, purchasing, sales, suppliers and day-to-day financial activity. The solution can be tailored to the workflows, reports and access controls of the organization.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Custom solution',
            'featured' => false,
            'show_on_homepage' => false,
            'sort_order' => 40,
            'accent' => 'teal',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'Pharmacy Management System — Inventory, Expiry, Sales & Purchasing',
                'description' => 'Custom pharmacy management software for medicine inventory, batch and expiry tracking, suppliers, purchasing, sales, receivables and reporting.',
            ],
            'preview' => [
                'section' => 'Pharmacy operations',
                'title' => 'Medicine control',
                'status' => 'Custom',
                'metrics' => [
                    ['label' => 'Inventory', 'value' => 'Tracked', 'detail' => 'medicine stock'],
                    ['label' => 'Expiry', 'value' => 'Visible', 'detail' => 'batch awareness'],
                    ['label' => 'Purchasing', 'value' => 'Connected', 'detail' => 'supplier flow'],
                ],
                'rows' => ['Medicine & batch inventory', 'Supplier purchasing', 'Sales & receivables'],
            ],
            'highlights' => ['Batch and expiry visibility', 'Medicine inventory control', 'Purchasing and suppliers', 'Sales and financial reporting'],
            'problem' => [
                'title' => 'Pharmacy operations become risky when stock, expiry, purchasing and sales are managed in separate records.',
                'body' => [
                    'A pharmacy needs fast access to medicine availability while also knowing which batches are approaching expiry and what should be reordered.',
                    'BusinessOS can connect medicine inventory, suppliers, purchasing, sales, receivables and management reporting in one tailored workflow.',
                ],
            ],
            'features_intro' => [
                'title' => 'A pharmacy system built around operational control.',
                'description' => 'Modules can be configured around the exact medicine catalog, purchasing process, sales workflow and reporting needs of the business.',
            ],
            'features' => [
                ['title' => 'Medicine inventory', 'description' => 'Maintain medicine records, stock quantities, units and inventory movement in one searchable database.'],
                ['title' => 'Batch & expiry tracking', 'description' => 'Keep batch and expiry information visible so teams can monitor stock more carefully and plan replenishment.'],
                ['title' => 'Purchasing & suppliers', 'description' => 'Record suppliers, purchase activity and incoming stock while keeping procurement connected to inventory.'],
                ['title' => 'Sales workflow', 'description' => 'Support pharmacy sales with clear product lookup, stock deduction and transaction history.'],
                ['title' => 'Receivables & payments', 'description' => 'Track customer balances, payments and related financial activity when the business sells on account.'],
                ['title' => 'Reports & permissions', 'description' => 'Provide role-based access and management reports for stock, purchasing, sales and finance.'],
            ],
            'use_cases_intro' => [
                'title' => 'Useful for pharmacies that need more than a simple sales screen.',
                'description' => 'The system is suited to businesses that want medicine stock, purchasing and financial visibility to stay connected.',
            ],
            'use_cases' => ['Retail pharmacy inventory', 'Medicine expiry monitoring', 'Supplier purchasing', 'Sales and receivables', 'Stock reporting', 'Management visibility'],
            'spotlight' => [
                'kicker' => 'Custom implementation',
                'title' => 'Adapt the system to your pharmacy workflow.',
                'description' => 'BusinessOS can tailor fields, reports, roles and operational steps to the actual way the pharmacy works.',
                'items' => ['Configurable modules', 'Role-based access', 'Custom reports'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing based on scope',
                'pricing_note' => 'Pricing depends on modules, users, locations, data migration, integrations and deployment requirements.',
                'pricing_model' => 'Custom implementation',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Private deployment', 'Data migration and onboarding'],
            ],
            'final' => [
                'title' => 'Build a pharmacy system around the way your team actually works.',
                'description' => 'Request a discussion about inventory, expiry tracking, purchasing, sales and reporting requirements.',
            ],
            'faq' => [
                ['question' => 'Can the pharmacy system track medicine expiry dates?', 'answer' => 'Yes. The solution can be configured to store batch and expiry information and make expiring stock easier to review.'],
                ['question' => 'Can existing medicine and supplier data be migrated?', 'answer' => 'Yes. Data migration can be included after the source data is reviewed and mapped to the new system.'],
                ['question' => 'Can the system be customized for our pharmacy?', 'answer' => 'Yes. Modules, permissions, reports and workflows can be tailored to the business requirements.'],
            ],
        ],

        'raw-materials-db' => [
            'name' => 'Raw Materials Database',
            'slug' => 'raw-materials-db',
            'icon_letter' => 'R',
            'eyebrow' => 'Materials & Procurement Data',
            'headline' => 'Create one reliable source for raw material specifications, suppliers, rates and stock data.',
            'short_description' => 'A centralized raw materials database for specifications, units, suppliers, prices, landed costs, stock references, documents and purchasing history.',
            'description' => 'BusinessOS Raw Materials Database gives procurement, production and finance teams a shared source of truth for material records. It can centralize specifications, supplier information, units, rates, landed-cost references, documents and historical purchasing data.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Custom solution',
            'featured' => false,
            'show_on_homepage' => false,
            'sort_order' => 50,
            'accent' => 'blue',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'Raw Materials Database — Material Master, Suppliers, Rates & Procurement Data',
                'description' => 'Centralize raw material specifications, suppliers, units, prices, landed costs, stock references and purchase history in a searchable web database.',
            ],
            'preview' => [
                'section' => 'Materials data',
                'title' => 'Material master',
                'status' => 'Custom',
                'metrics' => [
                    ['label' => 'Materials', 'value' => 'Centralized', 'detail' => 'single source'],
                    ['label' => 'Suppliers', 'value' => 'Linked', 'detail' => 'procurement context'],
                    ['label' => 'Rates', 'value' => 'Historical', 'detail' => 'price visibility'],
                ],
                'rows' => ['Material specifications', 'Supplier & rate history', 'Documents & references'],
            ],
            'highlights' => ['Central material master', 'Supplier and rate history', 'Landed-cost references', 'Searchable technical records'],
            'problem' => [
                'title' => 'Raw material decisions slow down when specifications, prices and supplier records live in scattered spreadsheets.',
                'body' => [
                    'Procurement and production teams need a dependable material master that uses consistent names, units and specifications.',
                    'A centralized database reduces duplicate records and makes supplier, pricing and historical purchasing information easier to find and compare.',
                ],
            ],
            'features_intro' => [
                'title' => 'Structured material data that can support procurement, inventory and production.',
                'description' => 'The database can start as a focused materials master and expand into purchasing, costing, stock and production integrations.',
            ],
            'features' => [
                ['title' => 'Material master', 'description' => 'Maintain standardized material names, categories, units, specifications and internal references.'],
                ['title' => 'Supplier mapping', 'description' => 'Connect materials to approved or known suppliers with supplier-specific codes and notes.'],
                ['title' => 'Price history', 'description' => 'Store quoted or purchased rates over time for better procurement visibility.'],
                ['title' => 'Landed-cost references', 'description' => 'Capture transport and related cost components when the business needs landed-rate analysis.'],
                ['title' => 'Documents & specifications', 'description' => 'Attach technical documents, certificates, images or reference files to material records.'],
                ['title' => 'Import & integration', 'description' => 'Import existing spreadsheets and connect the material master to ERP, inventory or production systems.'],
            ],
            'use_cases_intro' => [
                'title' => 'A data foundation for companies that buy and consume many raw materials.',
                'description' => 'Use it as a searchable reference or connect it to procurement, costing and production workflows.',
            ],
            'use_cases' => ['Material specification library', 'Supplier comparison', 'Rate history', 'Procurement master data', 'Factory material references', 'ERP integration'],
            'spotlight' => [
                'kicker' => 'Data foundation',
                'title' => 'Clean material data before automating more complex workflows.',
                'description' => 'Standardized material records make later procurement, inventory, costing and production automation more reliable.',
                'items' => ['Consistent naming', 'Historical rates', 'Integration-ready'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing based on scope',
                'pricing_note' => 'Pricing depends on record volume, source files, required fields, migration complexity, users and integrations.',
                'pricing_model' => 'Database + implementation',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Private deployment', 'Spreadsheet migration and cleanup'],
            ],
            'final' => [
                'title' => 'Turn scattered material records into one dependable database.',
                'description' => 'Share your current spreadsheets or material workflow and we can design the data structure around them.',
            ],
            'faq' => [
                ['question' => 'Can you import raw material data from Excel?', 'answer' => 'Yes. Existing spreadsheets can be reviewed, cleaned, mapped and imported into the new material database.'],
                ['question' => 'Can this connect to an ERP or factory system?', 'answer' => 'Yes. The material master can be designed for integration with procurement, inventory, costing and production modules.'],
                ['question' => 'Can different material specifications and units be stored?', 'answer' => 'Yes. The database can be configured with the fields and units required by the business.'],
            ],
        ],

        'pvc-pipe-factory' => [
            'name' => 'PVC Pipe Factory Management',
            'slug' => 'pvc-pipe-factory',
            'icon_letter' => 'V',
            'eyebrow' => 'Manufacturing & Factory ERP',
            'headline' => 'Connect PVC pipe production, raw materials, costing, quality and finished stock.',
            'short_description' => 'A customizable PVC pipe factory system for production planning, formulations/BOMs, raw material consumption, quality checks, wastage, finished goods, costing and sales.',
            'description' => 'BusinessOS PVC Pipe Factory Management is a manufacturing solution for pipe factories that want production, raw materials, formulas or BOMs, wastage, quality control, finished goods and costing to work from the same operational data.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Custom solution',
            'featured' => false,
            'show_on_homepage' => false,
            'sort_order' => 60,
            'accent' => 'indigo',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'PVC Pipe Factory Management Software — Production, Materials, Costing & Inventory',
                'description' => 'Custom PVC pipe factory ERP for production planning, raw material consumption, BOMs/formulations, quality, wastage, finished stock, costing and sales.',
            ],
            'preview' => [
                'section' => 'Factory operations',
                'title' => 'Production control',
                'status' => 'Custom',
                'metrics' => [
                    ['label' => 'Production', 'value' => 'Planned', 'detail' => 'orders & runs'],
                    ['label' => 'Materials', 'value' => 'Consumed', 'detail' => 'actual usage'],
                    ['label' => 'Costing', 'value' => 'Connected', 'detail' => 'production value'],
                ],
                'rows' => ['Production orders', 'Material consumption', 'Finished goods & costing'],
            ],
            'highlights' => ['Production planning', 'BOM/formulation control', 'Actual material consumption', 'Costing and finished goods'],
            'problem' => [
                'title' => 'Factory profitability is difficult to understand when production, materials and finished stock are recorded separately.',
                'body' => [
                    'PVC pipe production needs accurate material usage, product sizes and formulations to stay connected to output and costing.',
                    'A tailored factory system can connect production orders, actual consumption, wastage, quality records, finished inventory and financial reporting.',
                ],
            ],
            'features_intro' => [
                'title' => 'Manufacturing workflows designed around the production floor.',
                'description' => 'The system can be configured for the factory’s pipe sizes, formulations, machines, warehouses, approval steps and costing method.',
            ],
            'features' => [
                ['title' => 'Production planning', 'description' => 'Create production orders by product, size, quantity, line, shift or required date.'],
                ['title' => 'BOMs & formulations', 'description' => 'Define standard raw material formulas or BOMs by product and production specification.'],
                ['title' => 'Actual consumption', 'description' => 'Record actual material usage and compare it with planned quantities to identify variances.'],
                ['title' => 'Quality & wastage', 'description' => 'Capture quality checks, rejects, scrap and production wastage when required.'],
                ['title' => 'Finished goods inventory', 'description' => 'Move completed production into finished stock and maintain traceable inventory movement.'],
                ['title' => 'Production costing', 'description' => 'Connect material consumption and other configured costs to production and profitability reporting.'],
            ],
            'use_cases_intro' => [
                'title' => 'Suitable for PVC pipe factories moving from spreadsheets to integrated production control.',
                'description' => 'Modules can start with production and materials, then expand into procurement, sales, finance and maintenance.',
            ],
            'use_cases' => ['PVC pipe production orders', 'Formula/BOM management', 'Raw material usage', 'Wastage tracking', 'Finished goods inventory', 'Factory costing'],
            'spotlight' => [
                'kicker' => 'Factory-specific',
                'title' => 'Configure the software around the actual production process.',
                'description' => 'BusinessOS focuses on the factory’s real products, measurements, materials, approval steps and costing rules instead of forcing a generic ERP workflow.',
                'items' => ['Production-driven', 'Material-aware', 'Costing-ready'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing based on factory scope',
                'pricing_note' => 'Pricing depends on modules, warehouses, production lines, users, migration, reporting and integration requirements.',
                'pricing_model' => 'Custom factory implementation',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Private deployment', 'Onboarding and historical data migration'],
            ],
            'final' => [
                'title' => 'Connect the production floor to inventory and costing.',
                'description' => 'Tell us how your factory plans production, consumes materials and records finished pipe so the system can match the workflow.',
            ],
            'faq' => [
                ['question' => 'Can the system support different PVC pipe sizes and formulations?', 'answer' => 'Yes. Products, dimensions, formulas or BOMs can be configured around the factory’s production requirements.'],
                ['question' => 'Can planned and actual raw material usage be compared?', 'answer' => 'Yes. The workflow can capture actual consumption and report variances against standard or planned quantities.'],
                ['question' => 'Can this include inventory and accounting?', 'answer' => 'Yes. The factory solution can be integrated with procurement, warehouses, sales and financial modules as required.'],
            ],
        ],

        'financial-systems' => [
            'name' => 'Financial Management Systems',
            'slug' => 'financial-systems',
            'icon_letter' => 'A',
            'eyebrow' => 'Accounting & Financial Control',
            'headline' => 'Build a financial system around your ledgers, cash flow, receivables and reporting needs.',
            'short_description' => 'Custom financial systems for chart of accounts, journals, ledgers, cash and bank, receivables, payables, expenses, approvals, closing and management reports.',
            'description' => 'BusinessOS Financial Management Systems can be tailored for organizations that need reliable accounting workflows, cash and bank control, receivables, payables, expense management, approvals and management reporting without forcing the business into an unsuitable off-the-shelf structure.',
            'category' => 'FinanceApplication',
            'application_category' => 'FinanceApplication',
            'operating_system' => 'Web',
            'platforms' => ['Web'],
            'status' => 'Custom solution',
            'featured' => false,
            'show_on_homepage' => false,
            'sort_order' => 70,
            'accent' => 'green',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'Custom Financial Management System — Accounting, Ledgers, Cash & Reporting',
                'description' => 'Custom web-based financial systems for accounting, ledgers, journals, cash and bank, receivables, payables, expenses, approvals and management reports.',
            ],
            'preview' => [
                'section' => 'Financial control',
                'title' => 'Accounts overview',
                'status' => 'Custom',
                'metrics' => [
                    ['label' => 'Ledgers', 'value' => 'Structured', 'detail' => 'account activity'],
                    ['label' => 'Cash', 'value' => 'Controlled', 'detail' => 'cash & bank'],
                    ['label' => 'Reports', 'value' => 'Connected', 'detail' => 'management view'],
                ],
                'rows' => ['Journal & ledger entries', 'Receivables & payables', 'Financial reports'],
            ],
            'highlights' => ['Chart of accounts and ledgers', 'Cash and bank control', 'Receivables and payables', 'Financial and management reports'],
            'problem' => [
                'title' => 'Financial control weakens when accounting records, operational balances and approvals are spread across disconnected files.',
                'body' => [
                    'Management needs dependable financial records that can be traced from transactions to ledgers and reports.',
                    'A custom financial system can reflect the organization’s account structure, approval process, currencies, fiscal periods and reporting requirements.',
                ],
            ],
            'features_intro' => [
                'title' => 'Financial software aligned with the organization’s actual controls.',
                'description' => 'The implementation can range from focused cash and ledger management to a broader accounting system integrated with ERP operations.',
            ],
            'features' => [
                ['title' => 'Chart of accounts', 'description' => 'Configure account structures, categories and opening balances around the organization’s reporting needs.'],
                ['title' => 'Journals & ledgers', 'description' => 'Record financial entries with traceable posting to account ledgers and transaction history.'],
                ['title' => 'Cash & bank', 'description' => 'Track cash accounts, bank activity, transfers and configured approval controls.'],
                ['title' => 'Receivables & payables', 'description' => 'Maintain customer and supplier balances with payment and settlement history.'],
                ['title' => 'Expenses & approvals', 'description' => 'Record categorized expenses and route financial actions through approval workflows when required.'],
                ['title' => 'Financial reporting', 'description' => 'Produce configured trial balance, account statements and management reports from structured financial data.'],
            ],
            'use_cases_intro' => [
                'title' => 'A foundation for finance teams that need control, traceability and tailored reporting.',
                'description' => 'Use it alone or integrate finance with purchasing, sales, inventory, projects or production.',
            ],
            'use_cases' => ['General accounting', 'Cash management', 'Customer receivables', 'Supplier payables', 'Expense control', 'Management reporting'],
            'spotlight' => [
                'kicker' => 'Financial architecture',
                'title' => 'Match the system to the organization’s accounting structure.',
                'description' => 'Accounts, approvals, reporting dimensions and integrations can be designed around the way finance is actually managed.',
                'items' => ['Traceable entries', 'Configurable controls', 'Integrated reporting'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing based on scope',
                'pricing_note' => 'Pricing depends on accounting modules, entities, currencies, users, historical migration, reporting and integrations.',
                'pricing_model' => 'Custom financial implementation',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Private deployment', 'Opening balance and historical data migration'],
            ],
            'final' => [
                'title' => 'Build financial control around clean, traceable data.',
                'description' => 'Share your chart of accounts, reporting needs and current workflow so we can design the right financial system.',
            ],
            'faq' => [
                ['question' => 'Can the financial system be integrated with ERP modules?', 'answer' => 'Yes. Finance can be connected to sales, purchasing, inventory, production or other operational modules when required.'],
                ['question' => 'Can existing accounting data be migrated?', 'answer' => 'Yes. Historical balances and transactions can be migrated after source data, mapping and reconciliation requirements are reviewed.'],
                ['question' => 'Can approval workflows and reports be customized?', 'answer' => 'Yes. Approval steps, account structures and reports can be tailored to the organization.'],
            ],
        ],
        'restaurant-management' => [
            'name' => 'Restaurant Management System',
            'slug' => 'restaurant-management',
            'icon_letter' => 'R',
            'eyebrow' => 'Restaurant Operations & Waiter Ordering',
            'headline' => 'Let waiters take table orders on a mobile app and send them directly into the restaurant and kitchen workflow.',
            'short_description' => 'A restaurant management platform where waiters take table orders through a mobile app and send them directly to the kitchen, with table management, menu control, billing, payments and reporting.',
            'description' => 'BusinessOS Restaurant Management System is designed for use inside the restaurant. Waiters take customer orders at the table through a mobile app, and those orders are sent directly into the restaurant dashboard and kitchen workflow with table context, order status, menu control, billing, payments and reporting.',
            'category' => 'BusinessApplication',
            'application_category' => 'BusinessApplication',
            'operating_system' => 'Web, Android & iOS',
            'platforms' => ['Web Admin', 'Waiter Mobile App', 'Kitchen Display'],
            'status' => 'Custom solution',
            'featured' => false,
            'show_on_homepage' => false,
            'sort_order' => 80,
            'accent' => 'orange',
            'updated_at' => '2026-09-25',
            'seo' => [
                'title' => 'Restaurant Management System — Waiter Mobile Ordering, Tables & Kitchen',
                'description' => 'Restaurant management software with waiter mobile ordering, table management, kitchen workflow, menu control, billing, payments and reporting.',
            ],
            'preview' => [
                'section' => 'Restaurant operations',
                'title' => 'Live order flow',
                'status' => 'Custom',
                'metrics' => [
                    ['label' => 'Waiter orders', 'value' => 'Live', 'detail' => 'table service'],
                    ['label' => 'Kitchen', 'value' => 'Connected', 'detail' => 'order queue'],
                    ['label' => 'Status', 'value' => 'Tracked', 'detail' => 'order lifecycle'],
                ],
                'rows' => ['New table orders', 'Kitchen preparation queue', 'Ready / served / completed'],
            ],
            'highlights' => ['Waiter mobile ordering', 'Table transfer, merge & split billing', 'Kitchen stations & KOT workflow', 'Cashier closing & approval controls'],
            'problem' => [
                'title' => 'Restaurant operations become harder to coordinate when waiters, kitchen staff, tables and billing are handled through separate or manual processes.',
                'body' => [
                    'Waiters need a fast way to take orders at the table without returning to a fixed terminal or relying on paper tickets. Each order should enter the same operational workflow used by the kitchen and cashier.',
                    'BusinessOS can connect the waiter mobile app, table order, kitchen preparation, serving status, billing, payments, menu availability and reporting so every order has a clear lifecycle from table to completion.',
                ],
            ],
            'features_intro' => [
                'title' => 'A connected ordering workflow from the waiter’s phone to the kitchen.',
                'description' => 'The core workflow is dine-in table service, with optional takeaway handling if the restaurant needs it.',
            ],
            'features' => [
                ['title' => 'Waiter mobile ordering', 'description' => 'Waiters select the table, browse the live menu, add items, modifiers and notes, then submit the order directly from a mobile application while serving customers.'],
                ['title' => 'Live order reception', 'description' => 'Waiter-submitted orders appear immediately in the restaurant dashboard and kitchen workflow with table number, waiter, items, quantities and notes.'],
                ['title' => 'Kitchen stations & KOT', 'description' => 'Route ordered items to the correct kitchen or preparation station and support kitchen display screens or printed Kitchen Order Tickets (KOT).'],
                ['title' => 'Kitchen order flow', 'description' => 'Track each order through states such as new, accepted, preparing, ready, served, completed or cancelled.'],
                ['title' => 'Menu & availability', 'description' => 'Manage categories, items, prices, variants, modifiers, add-ons and temporary availability centrally for all waiter devices.'],
                ['title' => 'Table management', 'description' => 'Track tables, active orders, waiter assignment, occupancy and service status across restaurant areas or floors.'],
                ['title' => 'Transfer & merge tables', 'description' => 'Move an active order to another table or merge tables and their open orders when guests change seating arrangements.'],
                ['title' => 'Split bills', 'description' => 'Split a table bill by item, guest or amount when customers want to pay separately.'],
                ['title' => 'Waiter shifts & accountability', 'description' => 'Open and close waiter shifts and retain waiter responsibility for orders, changes, void requests and sales activity.'],
                ['title' => 'Void, cancellation & complimentary controls', 'description' => 'Require authorized approval for cancelled items, voided orders, complimentary items or discounts, with reason and audit history.'],
                ['title' => 'Billing & payments', 'description' => 'Generate bills from table orders, apply approved discounts, record one or multiple payments and close the table only after settlement.'],
                ['title' => 'Cashier closing', 'description' => 'Close cashier shifts with expected versus counted cash, payment-method totals, voids, discounts and closing variance.'],
                ['title' => 'Restaurant reporting', 'description' => 'Report sales, order volume, popular items, waiter activity, table turnover, discounts, voids, complimentary items and cashier closing results.'],
            ],
            'use_cases_intro' => [
                'title' => 'Designed for restaurants that want waiters to take orders digitally without slowing table service.',
                'description' => 'The waiter mobile app becomes the front-of-house order entry point while kitchen, cashier and management stay connected to the same order.',
            ],
            'use_cases' => ['Waiter table ordering', 'Table transfer and merge', 'Split billing', 'Kitchen stations and KOT printing', 'Waiter shift control', 'Void and complimentary approvals', 'Cashier closing', 'Restaurant sales reporting'],
            'spotlight' => [
                'kicker' => 'Waiter-to-kitchen workflow',
                'title' => 'Every customer order moves through one visible lifecycle.',
                'description' => 'The restaurant can see when a waiter submits an order, which kitchen station receives each item, when preparation is complete, when the order is served, and how the table is finally billed and closed.',
                'items' => ['Waiter mobile app', 'Kitchen/KOT routing', 'Table & cashier control'],
            ],
            'commercial' => [
                'pricing_status' => 'Pricing based on restaurant scope',
                'pricing_note' => 'Pricing depends on locations, number of waiters, table areas, kitchen stations, KOT printing or displays, billing controls, cashier closing, payment integrations and reporting.',
                'pricing_model' => 'Restaurant platform + mobile app',
                'pricing_plans' => [],
                'deployment_options' => ['BusinessOS-hosted deployment', 'Private deployment', 'Waiter mobile application'],
            ],
            'final' => [
                'title' => 'Turn waiter orders into a fast, controlled restaurant workflow.',
                'description' => 'Tell us how waiters take table orders today, how the kitchen receives tickets, how tables are billed and how many service areas or locations you need to manage.',
            ],
            'faq' => [
                ['question' => 'Who uses the mobile ordering app?', 'answer' => 'The mobile app is for restaurant waiters. Waiters use it at the table to enter customer orders and send them directly into the restaurant and kitchen workflow.'],
                ['question' => 'Will waiter orders appear automatically in the kitchen?', 'answer' => 'Yes. Submitted table orders can flow immediately into the restaurant dashboard and kitchen queue with table information, item details and preparation status.'],
                ['question' => 'Can the system manage tables and waiter assignments?', 'answer' => 'Yes. The implementation can track tables, active orders and waiter responsibility so front-of-house and management have a clear live view.'],
                ['question' => 'Can tables be transferred or merged?', 'answer' => 'Yes. Active orders can be moved between tables or merged when guests change seating or combine tables.'],
                ['question' => 'Can a bill be split?', 'answer' => 'Yes. Bills can be split by item, guest or amount depending on the restaurant workflow.'],
                ['question' => 'Can different foods be sent to different kitchen stations?', 'answer' => 'Yes. Menu items can be routed to configured preparation stations and shown on kitchen displays or printed as KOT tickets.'],
                ['question' => 'Are voids, cancellations and complimentary items controlled?', 'answer' => 'Yes. These actions can require manager approval, reason capture and audit history so staff cannot silently remove chargeable items.'],
                ['question' => 'Does the system support waiter and cashier shifts?', 'answer' => 'Yes. Waiter activity can be tracked by shift, and cashier closing can compare expected payments with counted amounts and closing variance.'],
                ['question' => 'Can menu items be made unavailable without updating every waiter device?', 'answer' => 'Yes. Menu availability and pricing can be controlled centrally so waiter devices use the current restaurant menu.'],
            ],
        ],
    ],
];
